### ISSUE TITLE
Videojs and modal windows

### ISSUE THREAD

**Issue by Miguelrn** [spchuang/videojs-markers#70]
Hello everyone!
I'm trying to figure out why markers are not loading when videojs is loaded inside a modal window (boostrap), the problem is like the following:
i made two buttons, each of them load a diferrent video source and markers, when click on the first one load video and markers right but click on the second button just load video and not markers.
here its the error i get in the second click: Uncaught TypeError: videojs(...).markers is not a function.

here its a small demo:

https://jsfiddle.net/Pomer/3ecuzj98/6/

Anyone can figure what im doing wrong? thx !

**Comment by spchuang** [comment]
Hi @Miguelrn, the issue is with not properly destroying the markers instance. Ideally, the plugin should automatically detect when the video source has changed and act accordingly (i.e. auto remove plugin, or remove markers). This is what we can do right now:

whenever we start a new video, we destroy the marker plugin and reinitialize. Notice that the `player.marker` object is different before and after the initialization (before `player.markers` is a function, whereas afterwards, it's an object without multiple method functions)
Here is a working demo for your need: https://jsfiddle.net/tk2yuz92/1/
