### ISSUE TITLE
does this work in mobile browsers?

### ISSUE THREAD

**Issue by kunjan13** [spchuang/videojs-markers#72]
As i have tried in playing iphone chrome and safari browser it does not work. When i tap on markers it just shows information of chapter but it does not seek to that chapter.

**Comment by vhmth** [comment]
@kunjan13 when implementing this on [Loom](https://www.useloom.com] for markers in our comments system, we actually don't show the markers on mobile on purpose since the tap area is so small. I haven't actually tested this against that, but it may be that we'd have to register tap events on top of click events.

**Comment by spchuang** [comment]
I haven't really tested this on mobile browsers so it likely doesn't work very well. I believe it is possible to add support for mobile browser with some testing but I haven't had the time to actively supporting new cases so if you are interested, you're more than welcomed to help :)
